{{- if empty .Values.core.databaseSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-encryption-key
type: Opaque
data:
  ENCRYPTION_KEY: {{ include "cryostat.databasePassword" . }}
{{- end -}}
