{{- if empty .Values.storage.storageSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cryostat.deploymentName" . }}-storage-secret
  labels:
    {{- include "cryostat.labels" $ | nindent 4 }}
type: Opaque
data:
  STORAGE_ACCESS_KEY_ID: {{ b64enc "cryostat" }}
  STORAGE_ACCESS_KEY: {{ include "cryostat.objectStorageSecretKey" . }}
{{- end -}}
