{{- if empty .Values.core.databaseSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-storage-secret-key
type: Opaque
data:
  SECRET_KEY: {{ include "cryostat.objectStorageSecretKey" . }}
{{- end -}}
